### ISSUE TITLE
问题：“常见问题”与《中文用户指南》的定位区别

### ISSUE THREAD

**Issue by YDX-2147483647** [typst-doc-cn/guide#10]
请问这两个网页的定位是否有区别？如果没有，能否统一迁移到此仓库？

- 此仓库的[常见问题 | Typst 中文社区导航（`/guide/FAQ.html`）](https://typst-doc-cn.github.io/guide/FAQ.html)
- https://github.com/typst-doc-cn/typst-doc-cn.github.io 的[常见 Q&A - 中文用户指南 – Typst 中文文档（`/docs/chinese/#question-and-answer`）](https://typst-doc-cn.github.io/docs/chinese/#question-and-answer)

现在前者较丰富，但并不完全覆盖后者，导致有时要搜索两遍，不太方便。如果有可能，希望改进一下；需要的话我也可以提交 PR。

**Comment by flaribbit** [comment]
好的呀~

typst-doc-cn 的 Q&A 是早期编写的，已经很久没有更新了。

本仓库的 FAQ 主要来自于 QQ 群里的日经问题，有比较有意思的问题/方案就会同步到这个仓库里，希望能帮到后来人。前人栽树后人乘凉。

不过我平时也比较忙，这份文档是业余时间维护的，有诸多不完美之处，欢迎共同建设。
